// <auto-generated />
using System;
using APITest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APITest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("APITest.Models.Login", b =>
            {
                b.Property<int>("LogId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("Log_id");

                b.Property<int>("Extension")
                    .HasColumnType("int")
                    .HasColumnName("Extension");

                b.Property<DateTime>("Fecha")
                    .HasColumnType("datetime2")
                    .HasColumnName("fecha");

                b.Property<int>("TipoMov")
                    .HasColumnType("int");

                b.Property<int>("UserId")
                    .HasColumnType("int")
                    .HasColumnName("User_id");

                b.HasKey("LogId");

                b.ToTable("ccloglogin");
            });
#pragma warning restore 612, 618
        }
    }
}
